#!/bin/sh

set -e

KODA_CONFIGURATION_FILE=/etc/koda/koda.conf
KODA_GROUP="koda"
KODA_DATA_DIR=/var/lib/koda
KODA_LOG_DIR=/var/log/koda
KODA_USER="koda"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^koda:"; then
            adduser --system --home $KODA_DATA_DIR --quiet --group $KODA_USER
            # Data dir
            chown $KODA_USER:$KODA_GROUP $KODA_DATA_DIR
        fi
        # Register "$KODA_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $KODA_USER" 2> /dev/null || true
        # Configuration file
        chown $KODA_USER:$KODA_GROUP $KODA_CONFIGURATION_FILE
        chmod 0640 $KODA_CONFIGURATION_FILE
        # Log
        mkdir -p $KODA_LOG_DIR
        chown $KODA_USER:$KODA_GROUP $KODA_LOG_DIR
        chmod 0750 $KODA_LOG_DIR
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
